---
extends:
  - 'semistandard'

ignorePatterns:
  - '***/*.old.*'

rules:
  comma-dangle:
    - 2
    - 'always-multiline'
  space-before-function-paren: 
    - error
    -
      anonymous: never
      named: never
      asyncArrow: always